import argparse
from pathlib import Path

import yaml


def generate_policy(config: dict) -> str:
    budgets = config["budgets"]
    cost_increase = config["cost_increase"]
    resources = config["resources"]

    lines = [
        "package infracost",
        "",
        "import rego.v1",
        "",
        "",
        "# Generated automatically by policy-generator.",
        "# Do not edit this file manually.",
        "",
    ]

    for environment, values in budgets.items():
        limit = float(values["monthly_limit"])

        lines.extend(
            [
                f"deny contains out if {{",
                f'    input.environment == "{environment}"',
                "    actualCost := to_number(input.totalMonthlyCost)",
                f"    actualCost >= {limit}",
                "",
                "    out := {",
                f'        "policy": "monthly-budget-{environment}",',
                f'        "msg": sprintf("Monthly infrastructure cost for {environment} must be less than ${limit:.2f} (actual cost is $%.2f)", [actualCost]),',
                '        "failed": true,',
                "    }",
                "}",
                "",
            ]
        )

    if cost_increase.get("enabled", False):
        max_percentage = float(cost_increase["max_percentage"])

        lines.extend(
            [
                "deny contains out if {",
                "    current := to_number(input.totalMonthlyCost)",
                "    previous := to_number(input.pastTotalMonthlyCost)",
                "    previous > 0",
                "    increase := ((current - previous) / previous) * 100",
                f"    increase > {max_percentage}",
                "",
                "    out := {",
                '        "policy": "cost-increase-guardrail",',
                f'        "msg": sprintf("Monthly infrastructure cost increased by %.2f%%, exceeding the allowed {max_percentage:.2f}%%", [increase]),',
                '        "failed": true,',
                "    }",
                "}",
                "",
            ]
        )

    for resource_type, values in resources.items():
        if not values.get("enabled", False):
            continue

        limit = float(values["max_monthly_cost"])

        lines.extend(
            [
                "deny contains out if {",
                "    resource := input.projects[_].breakdown.resources[_]",
                f'    contains(lower(resource.name), "{resource_type}")',
                "    cost := to_number(resource.monthlyCost)",
                f"    cost >= {limit}",
                "",
                "    out := {",
                f'        "policy": "resource-cost-{resource_type}",',
                f'        "msg": sprintf("{resource_type} resource cost must be less than ${limit:.2f} (actual cost is $%.2f)", [cost]),',
                '        "failed": true,',
                "    }",
                "}",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate OPA/Rego FinOps policies from YAML configuration."
    )
    parser.add_argument(
        "--config",
        required=True,
        help="Path to policies.yml",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output Rego policy path",
    )

    args = parser.parse_args()

    config_path = Path(args.config)
    output_path = Path(args.output)

    with config_path.open("r", encoding="utf-8") as file:
        config = yaml.safe_load(file)

    policy = generate_policy(config)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(policy, encoding="utf-8")

    print(f"Generated policy: {output_path}")


if __name__ == "__main__":
    main()
